environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew :swing:downloadFiraCode --info
  - gradlew :swing:fatJar --info
#

artifacts:
  - path: 'swing\build\libs\*.jar'
    name: snapshot
#
